version: '3.1'

services:

  wordpress:
    image: wordpress:6
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin@123
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - /var/www/html:/var/www/html

  db:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /var/lib/mysql:/var/lib/mysql

volumes:
  wordpress:
  db:

